### PR TITLE
required params validation for anonymous track

### PR DESCRIPTION
**Pull request by gingerlime**
* raises a MissingIdAttributeError if recipient is missing from
  anonymous_track
* added a spec

### CODE REVIEW

**Comment by gingerlime** [comment]
... looks like this method is being re-used internally, so the validation breaks things. I'll try to fix this. I'm having trouble running specs though, which makes it difficult see #44

**Comment by gingerlime** [comment]
I think the specs I updated and the one I added work ok, but the failures on travis are unrelated to this change (related to #44).

**Comment by alisdair** [comment]
Thanks very much for taking the time to put together this PR. There's some internal discussion about this issue right now, and we're determining whether this behaviour (requiring `recipient` for anonymous tracked events) is a bug or not. I'll get back to you as soon as I have more.

**Comment by gingerlime** [comment]
Ok cool. I probably instigated this discussion talking to Wendy ;-)

Personally I would rather it wasn't required and give the user the flexibility to use whichever event attribute within the workflow. But I'm sure there are subtleties that only you guys know about.

Whatever you end up with, I hope the API enforces it clearly. (E.g. Rejects requests with missing required parameters etc)

**Comment by alisdair** [comment]
Thanks again for taking the time to create and submit this PR! Sorry about the delay in replying.

After much discussion we've decided not to make changes to the client libraries or API along the lines discussed here. I'd like to explain why.

As I think you're now aware, anonymous events only require a `recipient` field if you want the event to trigger a campaign. Events without a `recipient` are perfectly valid, and while we don't use them right now, we may want to process them differently in the future. So we can't add validation to require that `recipient` is present.

We also can't allow all anonymous events to trigger campaigns. Most of the anonymous events we receive are not intended for this use case, and evaluating them as such would be an enormous load on our back end systems for no significant benefit.

The good news is that we're working on some changes which would have made your life easier when trying to set up this campaign. In an upcoming platform release, anonymous events will be visible in the activity logs, and also visible in the event-triggered campaign page. That should at least make debugging easier.

I'm also fixing the documentation on using anonymous events to trigger campaigns to be much clearer about this use case.

**Pull request closed without merging**
