### PR TITLE
fix: show InvalidResponse error message in exception output

### PR DESCRIPTION
**Pull request by kjleitz**
Fixes https://github.com/customerio/customerio-ruby/issues/50

### CODE REVIEW

**Comment by kjleitz** [comment]
bump

**Comment by kjleitz** [comment]
bump?

**Comment by hownowstephen** [comment]
wow, looks like this one slipped through the cracks - sorry @kjleitz - will cut it into a patch release

**Comment by kjleitz** [comment]
thanks @hownowstephen!

**Pull request merged**
